name: CI

on:
  pull_request:
    branches:
      - master
    paths:
      - 'etc/ci/*'
      - 'src/*.toml'
  push:
    branches:
      - master
    paths:
      - 'etc/ci/*'
      - 'src/*.toml'
    tags-ignore:
      - '!v[0-9]+**'

jobs:
  build:
    name: Build ${{ matrix.fontname }} Font
    runs-on: ubuntu-latest
    strategy:
      matrix:
        fontname:
          - Iosevkins
          - IosevkinsMichi

    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends ttfautohint
      - uses: actions/checkout@v4
      - name: Fetch Submodules
        run: |
          git submodule update --init --recursive --depth 1
      - name: Setup
        run: |
          cat src/*.toml > lib/iosevka/private-build-plans.toml
          npm --prefix lib/iosevka install
      - name: Build
        run: |
          npm --prefix lib/iosevka run build -- ttf::${{ matrix.fontname }}
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.fontname }}
          path: lib/iosevka/dist/*

  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs:
      - build

    steps:
      - uses: actions/download-artifact@v4
      - name: Inspect Artifacts
        run:  ls -lFR
